### ISSUE TITLE
虽然是简单的静态页面

### ISSUE THREAD

**Issue by yeyuguo** [ShiningDan/react-animation-resume#1]
虽然是一个简单的静态页面，但是这个创意，我真的想说。6的飞起来，满分。大牛  其他开源还缺手下吗

**Comment by ShiningDan** [comment]
非常感谢点赞，原版创意是在  http://strml.net/ ，各种创意和显示优化都非常厉害，建议去看他的源代码。我只是用 React 仿照着写了一小部分基本功能，还有很多改进的余地。再次谢谢你的 Start
